// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr25JmOifrKtf5TljhHNX1FNZ5jlYS_GM',
    appId: '1:565871274416:web:6e32d433c9f125975a4e75',
    messagingSenderId: '565871274416',
    projectId: 'servisify-69e81',
    authDomain: 'servisify-69e81.firebaseapp.com',
    storageBucket: 'servisify-69e81.appspot.com',
    measurementId: 'G-QXFQL3GX9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd95MMnd-b30QDm2BP7Hlt_hcLvJsSQzg',
    appId: '1:565871274416:android:9339e927493a7ec05a4e75',
    messagingSenderId: '565871274416',
    projectId: 'servisify-69e81',
    storageBucket: 'servisify-69e81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuz4guatRIX_5JErIvmM7ZNBkrz1zcuoc',
    appId: '1:565871274416:ios:f188e467f8816ac55a4e75',
    messagingSenderId: '565871274416',
    projectId: 'servisify-69e81',
    storageBucket: 'servisify-69e81.appspot.com',
    iosBundleId: 'com.example.servisify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuz4guatRIX_5JErIvmM7ZNBkrz1zcuoc',
    appId: '1:565871274416:ios:1f7daf4b51e18d6b5a4e75',
    messagingSenderId: '565871274416',
    projectId: 'servisify-69e81',
    storageBucket: 'servisify-69e81.appspot.com',
    iosBundleId: 'com.example.servisify.RunnerTests',
  );
}
